# Generated by Django 5.0.6 on 2024-07-02 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfutureAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_completion', models.DateField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfutureAPI.volunteer')),
                ('volunteership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfutureAPI.volunteership')),
            ],
        ),
    ]
