# Generated by Django 5.0.6 on 2024-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfutureAPI', '0002_usercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='wfutureAPI\\static\\img\\pictures'),
        ),
    ]
