# Generated by Django 5.0.6 on 2024-07-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfutureAPI', '0004_alter_volunteer_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
